<Project>
	
	<PropertyGroup>
		
		<GameDirectory>C:\Program Files (x86)\Steam\steamapps\common\Subnautica</GameDirectory>
		
		<PluginsDirectory>$(GameDirectory)\BepInEx\plugins</PluginsDirectory>
		
		<DistDirectory>$(PluginsDirectory)\.dist</DistDirectory>
		
		<SevenZipExe>$(MSBuildThisFileDirectory).dependencies\tools\7z2601-extra\x64\7za.exe</SevenZipExe>
		
	</PropertyGroup>
	
</Project>